/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = InputMessage.Builder.class
)
public final class InputMessage {
  private final InputMessageRole role;

  private final String content;

  private final Map<String, Object> additionalProperties;

  private InputMessage(InputMessageRole role, String content,
      Map<String, Object> additionalProperties) {
    this.role = role;
    this.content = content;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Message author role
   */
  @JsonProperty("role")
  public InputMessageRole getRole() {
    return role;
  }

  /**
   * @return Message text
   */
  @JsonProperty("content")
  public String getContent() {
    return content;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof InputMessage && equalTo((InputMessage) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(InputMessage other) {
    return role.equals(other.role) && content.equals(other.content);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.role, this.content);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static RoleStage builder() {
    return new Builder();
  }

  public interface RoleStage {
    /**
     * <p>Message author role</p>
     */
    ContentStage role(@NotNull InputMessageRole role);

    Builder from(InputMessage other);
  }

  public interface ContentStage {
    /**
     * <p>Message text</p>
     */
    _FinalStage content(@NotNull String content);
  }

  public interface _FinalStage {
    InputMessage build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements RoleStage, ContentStage, _FinalStage {
    private InputMessageRole role;

    private String content;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(InputMessage other) {
      role(other.getRole());
      content(other.getContent());
      return this;
    }

    /**
     * <p>Message author role</p>
     * <p>Message author role</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("role")
    public ContentStage role(@NotNull InputMessageRole role) {
      this.role = Objects.requireNonNull(role, "role must not be null");
      return this;
    }

    /**
     * <p>Message text</p>
     * <p>Message text</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("content")
    public _FinalStage content(@NotNull String content) {
      this.content = Objects.requireNonNull(content, "content must not be null");
      return this;
    }

    @java.lang.Override
    public InputMessage build() {
      return new InputMessage(role, content, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
