/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class InputMessageRole {
  public static final InputMessageRole USER = new InputMessageRole(Value.USER, "user");

  public static final InputMessageRole SYSTEM = new InputMessageRole(Value.SYSTEM, "system");

  private final Value value;

  private final String string;

  InputMessageRole(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof InputMessageRole && this.string.equals(((InputMessageRole) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case USER:
        return visitor.visitUser();
      case SYSTEM:
        return visitor.visitSystem();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static InputMessageRole valueOf(String value) {
    switch (value) {
      case "user":
        return USER;
      case "system":
        return SYSTEM;
      default:
        return new InputMessageRole(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    USER,

    SYSTEM,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitUser();

    T visitSystem();

    T visitUnknown(String unknownType);
  }
}
