/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = OutputContentBlock.Builder.class
)
public final class OutputContentBlock {
  private final Optional<String> type;

  private final Optional<String> text;

  private final Map<String, Object> additionalProperties;

  private OutputContentBlock(Optional<String> type, Optional<String> text,
      Map<String, Object> additionalProperties) {
    this.type = type;
    this.text = text;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("type")
  public Optional<String> getType() {
    return type;
  }

  /**
   * @return Generated model output
   */
  @JsonProperty("text")
  public Optional<String> getText() {
    return text;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof OutputContentBlock && equalTo((OutputContentBlock) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(OutputContentBlock other) {
    return type.equals(other.type) && text.equals(other.text);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.type, this.text);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> type = Optional.empty();

    private Optional<String> text = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(OutputContentBlock other) {
      type(other.getType());
      text(other.getText());
      return this;
    }

    @JsonSetter(
        value = "type",
        nulls = Nulls.SKIP
    )
    public Builder type(Optional<String> type) {
      this.type = type;
      return this;
    }

    public Builder type(String type) {
      this.type = Optional.ofNullable(type);
      return this;
    }

    /**
     * <p>Generated model output</p>
     */
    @JsonSetter(
        value = "text",
        nulls = Nulls.SKIP
    )
    public Builder text(Optional<String> text) {
      this.text = text;
      return this;
    }

    public Builder text(String text) {
      this.text = Optional.ofNullable(text);
      return this;
    }

    public OutputContentBlock build() {
      return new OutputContentBlock(type, text, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
