/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = OutputMessage.Builder.class
)
public final class OutputMessage {
  private final Optional<String> type;

  private final Optional<String> role;

  private final Optional<List<OutputContentBlock>> content;

  private final Map<String, Object> additionalProperties;

  private OutputMessage(Optional<String> type, Optional<String> role,
      Optional<List<OutputContentBlock>> content, Map<String, Object> additionalProperties) {
    this.type = type;
    this.role = role;
    this.content = content;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("type")
  public Optional<String> getType() {
    return type;
  }

  @JsonProperty("role")
  public Optional<String> getRole() {
    return role;
  }

  @JsonProperty("content")
  public Optional<List<OutputContentBlock>> getContent() {
    return content;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof OutputMessage && equalTo((OutputMessage) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(OutputMessage other) {
    return type.equals(other.type) && role.equals(other.role) && content.equals(other.content);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.type, this.role, this.content);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> type = Optional.empty();

    private Optional<String> role = Optional.empty();

    private Optional<List<OutputContentBlock>> content = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(OutputMessage other) {
      type(other.getType());
      role(other.getRole());
      content(other.getContent());
      return this;
    }

    @JsonSetter(
        value = "type",
        nulls = Nulls.SKIP
    )
    public Builder type(Optional<String> type) {
      this.type = type;
      return this;
    }

    public Builder type(String type) {
      this.type = Optional.ofNullable(type);
      return this;
    }

    @JsonSetter(
        value = "role",
        nulls = Nulls.SKIP
    )
    public Builder role(Optional<String> role) {
      this.role = role;
      return this;
    }

    public Builder role(String role) {
      this.role = Optional.ofNullable(role);
      return this;
    }

    @JsonSetter(
        value = "content",
        nulls = Nulls.SKIP
    )
    public Builder content(Optional<List<OutputContentBlock>> content) {
      this.content = content;
      return this;
    }

    public Builder content(List<OutputContentBlock> content) {
      this.content = Optional.ofNullable(content);
      return this;
    }

    public OutputMessage build() {
      return new OutputMessage(type, role, content, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
