/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = Response.Builder.class
)
public final class Response {
  private final String id;

  private final String object;

  private final long created;

  private final String model;

  private final List<OutputMessage> output;

  private final Optional<TokenUsage> usage;

  private final Map<String, Object> additionalProperties;

  private Response(String id, String object, long created, String model, List<OutputMessage> output,
      Optional<TokenUsage> usage, Map<String, Object> additionalProperties) {
    this.id = id;
    this.object = object;
    this.created = created;
    this.model = model;
    this.output = output;
    this.usage = usage;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("object")
  public String getObject() {
    return object;
  }

  /**
   * @return Unix timestamp when the response was created
   */
  @JsonProperty("created")
  public long getCreated() {
    return created;
  }

  @JsonProperty("model")
  public String getModel() {
    return model;
  }

  @JsonProperty("output")
  public List<OutputMessage> getOutput() {
    return output;
  }

  @JsonProperty("usage")
  public Optional<TokenUsage> getUsage() {
    return usage;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof Response && equalTo((Response) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(Response other) {
    return id.equals(other.id) && object.equals(other.object) && created == other.created && model.equals(other.model) && output.equals(other.output) && usage.equals(other.usage);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.object, this.created, this.model, this.output, this.usage);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    ObjectStage id(@NotNull String id);

    Builder from(Response other);
  }

  public interface ObjectStage {
    CreatedStage object(@NotNull String object);
  }

  public interface CreatedStage {
    /**
     * <p>Unix timestamp when the response was created</p>
     */
    ModelStage created(long created);
  }

  public interface ModelStage {
    _FinalStage model(@NotNull String model);
  }

  public interface _FinalStage {
    Response build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage output(List<OutputMessage> output);

    _FinalStage addOutput(OutputMessage output);

    _FinalStage addAllOutput(List<OutputMessage> output);

    _FinalStage usage(Optional<TokenUsage> usage);

    _FinalStage usage(TokenUsage usage);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, ObjectStage, CreatedStage, ModelStage, _FinalStage {
    private String id;

    private String object;

    private long created;

    private String model;

    private Optional<TokenUsage> usage = Optional.empty();

    private List<OutputMessage> output = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(Response other) {
      id(other.getId());
      object(other.getObject());
      created(other.getCreated());
      model(other.getModel());
      output(other.getOutput());
      usage(other.getUsage());
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public ObjectStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("object")
    public CreatedStage object(@NotNull String object) {
      this.object = Objects.requireNonNull(object, "object must not be null");
      return this;
    }

    /**
     * <p>Unix timestamp when the response was created</p>
     * <p>Unix timestamp when the response was created</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("created")
    public ModelStage created(long created) {
      this.created = created;
      return this;
    }

    @java.lang.Override
    @JsonSetter("model")
    public _FinalStage model(@NotNull String model) {
      this.model = Objects.requireNonNull(model, "model must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage usage(TokenUsage usage) {
      this.usage = Optional.ofNullable(usage);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "usage",
        nulls = Nulls.SKIP
    )
    public _FinalStage usage(Optional<TokenUsage> usage) {
      this.usage = usage;
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllOutput(List<OutputMessage> output) {
      if (output != null) {
        this.output.addAll(output);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addOutput(OutputMessage output) {
      this.output.add(output);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "output",
        nulls = Nulls.SKIP
    )
    public _FinalStage output(List<OutputMessage> output) {
      this.output.clear();
      if (output != null) {
        this.output.addAll(output);
      }
      return this;
    }

    @java.lang.Override
    public Response build() {
      return new Response(id, object, created, model, output, usage, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
