/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = TextResponseConfig.Builder.class
)
public final class TextResponseConfig {
  private final Optional<TextResponseConfigFormat> format;

  private final Map<String, Object> additionalProperties;

  private TextResponseConfig(Optional<TextResponseConfigFormat> format,
      Map<String, Object> additionalProperties) {
    this.format = format;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("format")
  public Optional<TextResponseConfigFormat> getFormat() {
    return format;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof TextResponseConfig && equalTo((TextResponseConfig) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(TextResponseConfig other) {
    return format.equals(other.format);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.format);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<TextResponseConfigFormat> format = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(TextResponseConfig other) {
      format(other.getFormat());
      return this;
    }

    @JsonSetter(
        value = "format",
        nulls = Nulls.SKIP
    )
    public Builder format(Optional<TextResponseConfigFormat> format) {
      this.format = format;
      return this;
    }

    public Builder format(TextResponseConfigFormat format) {
      this.format = Optional.ofNullable(format);
      return this;
    }

    public TextResponseConfig build() {
      return new TextResponseConfig(format, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
