/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = TextResponseConfigFormat.Builder.class
)
public final class TextResponseConfigFormat {
  private final Optional<String> type;

  private final Map<String, Object> additionalProperties;

  private TextResponseConfigFormat(Optional<String> type,
      Map<String, Object> additionalProperties) {
    this.type = type;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Response format type (e.g. <code>text</code>)
   */
  @JsonProperty("type")
  public Optional<String> getType() {
    return type;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof TextResponseConfigFormat && equalTo((TextResponseConfigFormat) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(TextResponseConfigFormat other) {
    return type.equals(other.type);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.type);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> type = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(TextResponseConfigFormat other) {
      type(other.getType());
      return this;
    }

    /**
     * <p>Response format type (e.g. <code>text</code>)</p>
     */
    @JsonSetter(
        value = "type",
        nulls = Nulls.SKIP
    )
    public Builder type(Optional<String> type) {
      this.type = type;
      return this;
    }

    public Builder type(String type) {
      this.type = Optional.ofNullable(type);
      return this;
    }

    public TextResponseConfigFormat build() {
      return new TextResponseConfigFormat(type, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
