/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = TokenUsage.Builder.class
)
public final class TokenUsage {
  private final Optional<Integer> inputTokens;

  private final Optional<Integer> outputTokens;

  private final Optional<Integer> totalTokens;

  private final Map<String, Object> additionalProperties;

  private TokenUsage(Optional<Integer> inputTokens, Optional<Integer> outputTokens,
      Optional<Integer> totalTokens, Map<String, Object> additionalProperties) {
    this.inputTokens = inputTokens;
    this.outputTokens = outputTokens;
    this.totalTokens = totalTokens;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("input_tokens")
  public Optional<Integer> getInputTokens() {
    return inputTokens;
  }

  @JsonProperty("output_tokens")
  public Optional<Integer> getOutputTokens() {
    return outputTokens;
  }

  @JsonProperty("total_tokens")
  public Optional<Integer> getTotalTokens() {
    return totalTokens;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof TokenUsage && equalTo((TokenUsage) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(TokenUsage other) {
    return inputTokens.equals(other.inputTokens) && outputTokens.equals(other.outputTokens) && totalTokens.equals(other.totalTokens);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.inputTokens, this.outputTokens, this.totalTokens);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Integer> inputTokens = Optional.empty();

    private Optional<Integer> outputTokens = Optional.empty();

    private Optional<Integer> totalTokens = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(TokenUsage other) {
      inputTokens(other.getInputTokens());
      outputTokens(other.getOutputTokens());
      totalTokens(other.getTotalTokens());
      return this;
    }

    @JsonSetter(
        value = "input_tokens",
        nulls = Nulls.SKIP
    )
    public Builder inputTokens(Optional<Integer> inputTokens) {
      this.inputTokens = inputTokens;
      return this;
    }

    public Builder inputTokens(Integer inputTokens) {
      this.inputTokens = Optional.ofNullable(inputTokens);
      return this;
    }

    @JsonSetter(
        value = "output_tokens",
        nulls = Nulls.SKIP
    )
    public Builder outputTokens(Optional<Integer> outputTokens) {
      this.outputTokens = outputTokens;
      return this;
    }

    public Builder outputTokens(Integer outputTokens) {
      this.outputTokens = Optional.ofNullable(outputTokens);
      return this;
    }

    @JsonSetter(
        value = "total_tokens",
        nulls = Nulls.SKIP
    )
    public Builder totalTokens(Optional<Integer> totalTokens) {
      this.totalTokens = totalTokens;
      return this;
    }

    public Builder totalTokens(Integer totalTokens) {
      this.totalTokens = Optional.ofNullable(totalTokens);
      return this;
    }

    public TokenUsage build() {
      return new TokenUsage(inputTokens, outputTokens, totalTokens, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
