// This file was auto-generated by Fern from our API Definition.

import type * as ZerogpuApi from "../index.js";

/**
 * Chat completion payload (shape varies by model; extra fields allowed).
 */
export interface ChatCompletionResponse {
    id?: string | undefined;
    object?: string | undefined;
    created?: number | undefined;
    model?: string | undefined;
    choices?: Record<string, unknown>[] | undefined;
    usage?: ZerogpuApi.TokenUsage | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
