// This file was auto-generated by Fern from our API Definition.

export interface ChatMessage {
    /** Message role */
    role: ChatMessage.Role;
    /** Message text */
    content: string;
}

export namespace ChatMessage {
    /** Message role */
    export const Role = {
        System: "system",
        User: "user",
        Assistant: "assistant",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
}
