// This file was auto-generated by Fern from our API Definition.

export interface InputMessage {
    /** Message author role */
    role: InputMessage.Role;
    /** Message text */
    content: string;
}

export namespace InputMessage {
    /** Message author role */
    export const Role = {
        User: "user",
        System: "system",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
}
