// This file was auto-generated by Fern from our API Definition.

export interface OutputContentBlock {
    type?: string | undefined;
    /** Generated model output */
    text?: string | undefined;
}
