// This file was auto-generated by Fern from our API Definition.

export interface TokenUsage {
    input_tokens?: number | undefined;
    output_tokens?: number | undefined;
    total_tokens?: number | undefined;
}
