// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "sdk/core"
	internal "sdk/internal"
	option "sdk/option"
	responses "sdk/responses"
)

type Client struct {
	Responses *responses.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Responses: responses.NewClient(options),
		options:   options,
		baseURL:   options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
