/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.responses.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;
import types.InputMessage;
import types.TextResponseConfig;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateResponseRequest.Builder.class
)
public final class CreateResponseRequest {
  private final String model;

  private final List<InputMessage> input;

  private final Optional<TextResponseConfig> text;

  private final Map<String, Object> additionalProperties;

  private CreateResponseRequest(String model, List<InputMessage> input,
      Optional<TextResponseConfig> text, Map<String, Object> additionalProperties) {
    this.model = model;
    this.input = input;
    this.text = text;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Model identifier from the ZeroGPU dashboard (e.g. summarization or IAB classify).
   */
  @JsonProperty("model")
  public String getModel() {
    return model;
  }

  @JsonProperty("input")
  public List<InputMessage> getInput() {
    return input;
  }

  @JsonProperty("text")
  public Optional<TextResponseConfig> getText() {
    return text;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateResponseRequest && equalTo((CreateResponseRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateResponseRequest other) {
    return model.equals(other.model) && input.equals(other.input) && text.equals(other.text);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.model, this.input, this.text);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ModelStage builder() {
    return new Builder();
  }

  public interface ModelStage {
    /**
     * <p>Model identifier from the ZeroGPU dashboard (e.g. summarization or IAB classify).</p>
     */
    _FinalStage model(@NotNull String model);

    Builder from(CreateResponseRequest other);
  }

  public interface _FinalStage {
    CreateResponseRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage input(List<InputMessage> input);

    _FinalStage addInput(InputMessage input);

    _FinalStage addAllInput(List<InputMessage> input);

    _FinalStage text(Optional<TextResponseConfig> text);

    _FinalStage text(TextResponseConfig text);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ModelStage, _FinalStage {
    private String model;

    private Optional<TextResponseConfig> text = Optional.empty();

    private List<InputMessage> input = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreateResponseRequest other) {
      model(other.getModel());
      input(other.getInput());
      text(other.getText());
      return this;
    }

    /**
     * <p>Model identifier from the ZeroGPU dashboard (e.g. summarization or IAB classify).</p>
     * <p>Model identifier from the ZeroGPU dashboard (e.g. summarization or IAB classify).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("model")
    public _FinalStage model(@NotNull String model) {
      this.model = Objects.requireNonNull(model, "model must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage text(TextResponseConfig text) {
      this.text = Optional.ofNullable(text);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "text",
        nulls = Nulls.SKIP
    )
    public _FinalStage text(Optional<TextResponseConfig> text) {
      this.text = text;
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllInput(List<InputMessage> input) {
      if (input != null) {
        this.input.addAll(input);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addInput(InputMessage input) {
      this.input.add(input);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "input",
        nulls = Nulls.SKIP
    )
    public _FinalStage input(List<InputMessage> input) {
      this.input.clear();
      if (input != null) {
        this.input.addAll(input);
      }
      return this;
    }

    @java.lang.Override
    public CreateResponseRequest build() {
      return new CreateResponseRequest(model, input, text, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
