// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../core/index.js";
import * as errors from "../../errors/index.js";
import type * as ZerogpuApi from "../index.js";

export class MethodFailureError extends errors.ZerogpuApiError {
    constructor(body: ZerogpuApi.ErrorResponse, rawResponse?: core.RawResponse) {
        super({
            message: "MethodFailureError",
            statusCode: 420,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }

        this.name = this.constructor.name;
    }
}
