// This file was auto-generated by Fern from our API Definition.

import type * as ZerogpuApi from "../../../../index.js";

/**
 * @example
 *     {
 *         model: "model",
 *         messages: [{
 *                 role: "system",
 *                 content: "content"
 *             }]
 *     }
 */
export interface CreateChatCompletionRequest {
    /** Model identifier from the ZeroGPU dashboard. */
    model: string;
    messages: ZerogpuApi.ChatMessage[];
    /** Optional model-specific parameters (e.g. PII options). */
    metadata?: Record<string, unknown>;
}
