/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.responses;

import core.ClientOptions;
import core.RequestOptions;
import java.util.concurrent.CompletableFuture;
import resources.responses.requests.CreateResponseRequest;
import types.Response;

public class AsyncResponsesClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawResponsesClient rawClient;

  public AsyncResponsesClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawResponsesClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawResponsesClient withRawResponse() {
    return this.rawClient;
  }

  public CompletableFuture<Response> createResponse(CreateResponseRequest request) {
    return this.rawClient.createResponse(request).thenApply(response -> response.body());
  }

  public CompletableFuture<Response> createResponse(CreateResponseRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.createResponse(request, requestOptions).thenApply(response -> response.body());
  }
}
