/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.responses;

import core.ClientOptions;
import core.RequestOptions;
import resources.responses.requests.CreateResponseRequest;
import types.Response;

public class ResponsesClient {
  protected final ClientOptions clientOptions;

  private final RawResponsesClient rawClient;

  public ResponsesClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawResponsesClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawResponsesClient withRawResponse() {
    return this.rawClient;
  }

  public Response createResponse(CreateResponseRequest request) {
    return this.rawClient.createResponse(request).body();
  }

  public Response createResponse(CreateResponseRequest request, RequestOptions requestOptions) {
    return this.rawClient.createResponse(request, requestOptions).body();
  }
}
