# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .output_message import OutputMessage
from .token_usage import TokenUsage


class Response(UniversalBaseModel):
    id: str
    object: str
    created: int = pydantic.Field()
    """
    Unix timestamp when the response was created
    """

    model: str
    output: typing.List[OutputMessage]
    usage: typing.Optional[TokenUsage] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
