# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.input_message import InputMessage

CreateResponseRequestInput = typing.Union[str, typing.List[InputMessage]]
