// This file was auto-generated by Fern from our API Definition.

import { ChatClient } from "./api/resources/chat/client/Client.js";
import { ResponsesClient } from "./api/resources/responses/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace ZerogpuApiClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ZerogpuApiClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ZerogpuApiClient.Options>;
    protected _responses: ResponsesClient | undefined;
    protected _chat: ChatClient | undefined;

    constructor(options: ZerogpuApiClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get responses(): ResponsesClient {
        return (this._responses ??= new ResponsesClient(this._options));
    }

    public get chat(): ChatClient {
        return (this._chat ??= new ChatClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
