// This file was auto-generated by Fern from our API Definition.

export const ZerogpuApiEnvironment = {
    Production: "https://api.zerogpu.ai/v1",
} as const;

export type ZerogpuApiEnvironment = typeof ZerogpuApiEnvironment.Production;
