// This file was auto-generated by Fern from our API Definition.

import type * as ZerogpuApi from "../../../../index.js";

/**
 * @example
 *     {
 *         model: "model",
 *         input: "input"
 *     }
 */
export interface CreateResponseRequest {
    /** Model identifier from the ZeroGPU dashboard (e.g. summarization or IAB classify). */
    model: string;
    /**
     * Model-dependent input. Many production models accept a **plain string**.
     * Others accept a **chat-style message list** (`role` + `content`). Use the shape
     * required by your model; see [docs](https://docs.zerogpu.ai/api-reference/endpoint/responses).
     */
    input: CreateResponseRequest.Input;
    text?: ZerogpuApi.TextResponseConfig;
    /** Optional model-specific parameters (e.g. PII `mask`, `usecase`). Omit when not required. */
    metadata?: Record<string, unknown>;
}

export namespace CreateResponseRequest {
    /**
     * Model-dependent input. Many production models accept a **plain string**.
     * Others accept a **chat-style message list** (`role` + `content`). Use the shape
     * required by your model; see [docs](https://docs.zerogpu.ai/api-reference/endpoint/responses).
     */
    export type Input =
        /**
         * Plain text prompt or document text. */
        string | ZerogpuApi.InputMessage[];
}
