// This file was auto-generated by Fern from our API Definition.

import type * as ZerogpuApi from "../../../../index.js";

/**
 * @example
 *     {
 *         model: "model",
 *         input: [{
 *                 role: "user",
 *                 content: "content"
 *             }]
 *     }
 */
export interface CreateResponseRequest {
    /** Model identifier from the ZeroGPU dashboard (e.g. summarization or IAB classify). */
    model: string;
    input: ZerogpuApi.InputMessage[];
    text?: ZerogpuApi.TextResponseConfig;
}
