// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	core "sdk/core"
)

// Bad request — invalid body
type BadRequestError struct {
	*core.APIError
	Body any
}

func (b *BadRequestError) UnmarshalJSON(data []byte) error {
	var body any
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	b.StatusCode = 400
	b.Body = body
	return nil
}

func (b *BadRequestError) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.Body)
}

func (b *BadRequestError) Unwrap() error {
	return b.APIError
}

// Forbidden — invalid project ID or permissions
type ForbiddenError struct {
	*core.APIError
	Body any
}

func (f *ForbiddenError) UnmarshalJSON(data []byte) error {
	var body any
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	f.StatusCode = 403
	f.Body = body
	return nil
}

func (f *ForbiddenError) MarshalJSON() ([]byte, error) {
	return json.Marshal(f.Body)
}

func (f *ForbiddenError) Unwrap() error {
	return f.APIError
}

// Internal server error
type InternalServerError struct {
	*core.APIError
	Body any
}

func (i *InternalServerError) UnmarshalJSON(data []byte) error {
	var body any
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	i.StatusCode = 500
	i.Body = body
	return nil
}

func (i *InternalServerError) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.Body)
}

func (i *InternalServerError) Unwrap() error {
	return i.APIError
}

// Input exceeds model token limit (context_length_exceeded)
type MethodFailureError struct {
	*core.APIError
	Body ErrorResponse
}

func (m *MethodFailureError) UnmarshalJSON(data []byte) error {
	var body ErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	m.StatusCode = 420
	m.Body = body
	return nil
}

func (m *MethodFailureError) MarshalJSON() ([]byte, error) {
	return json.Marshal(m.Body)
}

func (m *MethodFailureError) Unwrap() error {
	return m.APIError
}

// Unauthorized — invalid or missing API key
type UnauthorizedError struct {
	*core.APIError
	Body any
}

func (u *UnauthorizedError) UnmarshalJSON(data []byte) error {
	var body any
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.StatusCode = 401
	u.Body = body
	return nil
}

func (u *UnauthorizedError) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

func (u *UnauthorizedError) Unwrap() error {
	return u.APIError
}
