// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "sdk/internal"
)

var (
	createResponseRequestFieldModel = big.NewInt(1 << 0)
	createResponseRequestFieldInput = big.NewInt(1 << 1)
	createResponseRequestFieldText  = big.NewInt(1 << 2)
)

type CreateResponseRequest struct {
	// Model identifier from the ZeroGPU dashboard (e.g. summarization or IAB classify).
	Model string              `json:"model" url:"-"`
	Input []*InputMessage     `json:"input" url:"-"`
	Text  *TextResponseConfig `json:"text,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateResponseRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetModel sets the Model field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateResponseRequest) SetModel(model string) {
	c.Model = model
	c.require(createResponseRequestFieldModel)
}

// SetInput sets the Input field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateResponseRequest) SetInput(input []*InputMessage) {
	c.Input = input
	c.require(createResponseRequestFieldInput)
}

// SetText sets the Text field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateResponseRequest) SetText(text *TextResponseConfig) {
	c.Text = text
	c.require(createResponseRequestFieldText)
}

func (c *CreateResponseRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateResponseRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateResponseRequest(body)
	return nil
}

func (c *CreateResponseRequest) MarshalJSON() ([]byte, error) {
	type embed CreateResponseRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	inputMessageFieldRole    = big.NewInt(1 << 0)
	inputMessageFieldContent = big.NewInt(1 << 1)
)

type InputMessage struct {
	// Message author role
	Role InputMessageRole `json:"role" url:"role"`
	// Message text
	Content string `json:"content" url:"content"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InputMessage) GetRole() InputMessageRole {
	if i == nil {
		return ""
	}
	return i.Role
}

func (i *InputMessage) GetContent() string {
	if i == nil {
		return ""
	}
	return i.Content
}

func (i *InputMessage) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *InputMessage) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetRole sets the Role field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InputMessage) SetRole(role InputMessageRole) {
	i.Role = role
	i.require(inputMessageFieldRole)
}

// SetContent sets the Content field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InputMessage) SetContent(content string) {
	i.Content = content
	i.require(inputMessageFieldContent)
}

func (i *InputMessage) UnmarshalJSON(data []byte) error {
	type unmarshaler InputMessage
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InputMessage(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InputMessage) MarshalJSON() ([]byte, error) {
	type embed InputMessage
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InputMessage) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// Message author role
type InputMessageRole string

const (
	InputMessageRoleUser   InputMessageRole = "user"
	InputMessageRoleSystem InputMessageRole = "system"
)

func NewInputMessageRoleFromString(s string) (InputMessageRole, error) {
	switch s {
	case "user":
		return InputMessageRoleUser, nil
	case "system":
		return InputMessageRoleSystem, nil
	}
	var t InputMessageRole
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i InputMessageRole) Ptr() *InputMessageRole {
	return &i
}

var (
	outputContentBlockFieldType = big.NewInt(1 << 0)
	outputContentBlockFieldText = big.NewInt(1 << 1)
)

type OutputContentBlock struct {
	Type *string `json:"type,omitempty" url:"type,omitempty"`
	// Generated model output
	Text *string `json:"text,omitempty" url:"text,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OutputContentBlock) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *OutputContentBlock) GetText() *string {
	if o == nil {
		return nil
	}
	return o.Text
}

func (o *OutputContentBlock) GetExtraProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.extraProperties
}

func (o *OutputContentBlock) require(field *big.Int) {
	if o.explicitFields == nil {
		o.explicitFields = big.NewInt(0)
	}
	o.explicitFields.Or(o.explicitFields, field)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OutputContentBlock) SetType(type_ *string) {
	o.Type = type_
	o.require(outputContentBlockFieldType)
}

// SetText sets the Text field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OutputContentBlock) SetText(text *string) {
	o.Text = text
	o.require(outputContentBlockFieldText)
}

func (o *OutputContentBlock) UnmarshalJSON(data []byte) error {
	type unmarshaler OutputContentBlock
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OutputContentBlock(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OutputContentBlock) MarshalJSON() ([]byte, error) {
	type embed OutputContentBlock
	var marshaler = struct {
		embed
	}{
		embed: embed(*o),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, o.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (o *OutputContentBlock) String() string {
	if o == nil {
		return "<nil>"
	}
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

var (
	outputMessageFieldType    = big.NewInt(1 << 0)
	outputMessageFieldRole    = big.NewInt(1 << 1)
	outputMessageFieldContent = big.NewInt(1 << 2)
)

type OutputMessage struct {
	Type    *string               `json:"type,omitempty" url:"type,omitempty"`
	Role    *string               `json:"role,omitempty" url:"role,omitempty"`
	Content []*OutputContentBlock `json:"content,omitempty" url:"content,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OutputMessage) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *OutputMessage) GetRole() *string {
	if o == nil {
		return nil
	}
	return o.Role
}

func (o *OutputMessage) GetContent() []*OutputContentBlock {
	if o == nil {
		return nil
	}
	return o.Content
}

func (o *OutputMessage) GetExtraProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.extraProperties
}

func (o *OutputMessage) require(field *big.Int) {
	if o.explicitFields == nil {
		o.explicitFields = big.NewInt(0)
	}
	o.explicitFields.Or(o.explicitFields, field)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OutputMessage) SetType(type_ *string) {
	o.Type = type_
	o.require(outputMessageFieldType)
}

// SetRole sets the Role field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OutputMessage) SetRole(role *string) {
	o.Role = role
	o.require(outputMessageFieldRole)
}

// SetContent sets the Content field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OutputMessage) SetContent(content []*OutputContentBlock) {
	o.Content = content
	o.require(outputMessageFieldContent)
}

func (o *OutputMessage) UnmarshalJSON(data []byte) error {
	type unmarshaler OutputMessage
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OutputMessage(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OutputMessage) MarshalJSON() ([]byte, error) {
	type embed OutputMessage
	var marshaler = struct {
		embed
	}{
		embed: embed(*o),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, o.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (o *OutputMessage) String() string {
	if o == nil {
		return "<nil>"
	}
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

var (
	responseFieldID      = big.NewInt(1 << 0)
	responseFieldObject  = big.NewInt(1 << 1)
	responseFieldCreated = big.NewInt(1 << 2)
	responseFieldModel   = big.NewInt(1 << 3)
	responseFieldOutput  = big.NewInt(1 << 4)
	responseFieldUsage   = big.NewInt(1 << 5)
)

type Response struct {
	ID     string `json:"id" url:"id"`
	Object string `json:"object" url:"object"`
	// Unix timestamp when the response was created
	Created int64            `json:"created" url:"created"`
	Model   string           `json:"model" url:"model"`
	Output  []*OutputMessage `json:"output" url:"output"`
	Usage   *TokenUsage      `json:"usage,omitempty" url:"usage,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *Response) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *Response) GetObject() string {
	if r == nil {
		return ""
	}
	return r.Object
}

func (r *Response) GetCreated() int64 {
	if r == nil {
		return 0
	}
	return r.Created
}

func (r *Response) GetModel() string {
	if r == nil {
		return ""
	}
	return r.Model
}

func (r *Response) GetOutput() []*OutputMessage {
	if r == nil {
		return nil
	}
	return r.Output
}

func (r *Response) GetUsage() *TokenUsage {
	if r == nil {
		return nil
	}
	return r.Usage
}

func (r *Response) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *Response) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *Response) SetID(id string) {
	r.ID = id
	r.require(responseFieldID)
}

// SetObject sets the Object field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *Response) SetObject(object string) {
	r.Object = object
	r.require(responseFieldObject)
}

// SetCreated sets the Created field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *Response) SetCreated(created int64) {
	r.Created = created
	r.require(responseFieldCreated)
}

// SetModel sets the Model field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *Response) SetModel(model string) {
	r.Model = model
	r.require(responseFieldModel)
}

// SetOutput sets the Output field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *Response) SetOutput(output []*OutputMessage) {
	r.Output = output
	r.require(responseFieldOutput)
}

// SetUsage sets the Usage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *Response) SetUsage(usage *TokenUsage) {
	r.Usage = usage
	r.require(responseFieldUsage)
}

func (r *Response) UnmarshalJSON(data []byte) error {
	type unmarshaler Response
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = Response(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *Response) MarshalJSON() ([]byte, error) {
	type embed Response
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *Response) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	textResponseConfigFieldFormat = big.NewInt(1 << 0)
)

type TextResponseConfig struct {
	Format *TextResponseConfigFormat `json:"format,omitempty" url:"format,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TextResponseConfig) GetFormat() *TextResponseConfigFormat {
	if t == nil {
		return nil
	}
	return t.Format
}

func (t *TextResponseConfig) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TextResponseConfig) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetFormat sets the Format field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TextResponseConfig) SetFormat(format *TextResponseConfigFormat) {
	t.Format = format
	t.require(textResponseConfigFieldFormat)
}

func (t *TextResponseConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler TextResponseConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TextResponseConfig(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TextResponseConfig) MarshalJSON() ([]byte, error) {
	type embed TextResponseConfig
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TextResponseConfig) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	textResponseConfigFormatFieldType = big.NewInt(1 << 0)
)

type TextResponseConfigFormat struct {
	// Response format type (e.g. `text`)
	Type *string `json:"type,omitempty" url:"type,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TextResponseConfigFormat) GetType() *string {
	if t == nil {
		return nil
	}
	return t.Type
}

func (t *TextResponseConfigFormat) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TextResponseConfigFormat) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TextResponseConfigFormat) SetType(type_ *string) {
	t.Type = type_
	t.require(textResponseConfigFormatFieldType)
}

func (t *TextResponseConfigFormat) UnmarshalJSON(data []byte) error {
	type unmarshaler TextResponseConfigFormat
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TextResponseConfigFormat(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TextResponseConfigFormat) MarshalJSON() ([]byte, error) {
	type embed TextResponseConfigFormat
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TextResponseConfigFormat) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	tokenUsageFieldInputTokens  = big.NewInt(1 << 0)
	tokenUsageFieldOutputTokens = big.NewInt(1 << 1)
	tokenUsageFieldTotalTokens  = big.NewInt(1 << 2)
)

type TokenUsage struct {
	InputTokens  *int `json:"input_tokens,omitempty" url:"input_tokens,omitempty"`
	OutputTokens *int `json:"output_tokens,omitempty" url:"output_tokens,omitempty"`
	TotalTokens  *int `json:"total_tokens,omitempty" url:"total_tokens,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TokenUsage) GetInputTokens() *int {
	if t == nil {
		return nil
	}
	return t.InputTokens
}

func (t *TokenUsage) GetOutputTokens() *int {
	if t == nil {
		return nil
	}
	return t.OutputTokens
}

func (t *TokenUsage) GetTotalTokens() *int {
	if t == nil {
		return nil
	}
	return t.TotalTokens
}

func (t *TokenUsage) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TokenUsage) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetInputTokens sets the InputTokens field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenUsage) SetInputTokens(inputTokens *int) {
	t.InputTokens = inputTokens
	t.require(tokenUsageFieldInputTokens)
}

// SetOutputTokens sets the OutputTokens field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenUsage) SetOutputTokens(outputTokens *int) {
	t.OutputTokens = outputTokens
	t.require(tokenUsageFieldOutputTokens)
}

// SetTotalTokens sets the TotalTokens field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TokenUsage) SetTotalTokens(totalTokens *int) {
	t.TotalTokens = totalTokens
	t.require(tokenUsageFieldTotalTokens)
}

func (t *TokenUsage) UnmarshalJSON(data []byte) error {
	type unmarshaler TokenUsage
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TokenUsage(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TokenUsage) MarshalJSON() ([]byte, error) {
	type embed TokenUsage
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TokenUsage) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}
