/**
 * This file was auto-generated by Fern from our API Definition.
 */

import core.ClientOptions;
import core.Suppliers;
import java.util.function.Supplier;
import resources.responses.AsyncResponsesClient;

public class AsyncZerogpuApiClient {
  protected final ClientOptions clientOptions;

  protected final Supplier<AsyncResponsesClient> responsesClient;

  public AsyncZerogpuApiClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.responsesClient = Suppliers.memoize(() -> new AsyncResponsesClient(clientOptions));
  }

  public AsyncResponsesClient responses() {
    return this.responsesClient.get();
  }

  public static AsyncZerogpuApiClientBuilder builder() {
    return new AsyncZerogpuApiClientBuilder();
  }
}
