/**
 * This file was auto-generated by Fern from our API Definition.
 */

import core.ClientOptions;
import core.Suppliers;
import java.util.function.Supplier;
import resources.responses.ResponsesClient;

public class ZerogpuApiClient {
  protected final ClientOptions clientOptions;

  protected final Supplier<ResponsesClient> responsesClient;

  public ZerogpuApiClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.responsesClient = Suppliers.memoize(() -> new ResponsesClient(clientOptions));
  }

  public ResponsesClient responses() {
    return this.responsesClient.get();
  }

  public static ZerogpuApiClientBuilder builder() {
    return new ZerogpuApiClientBuilder();
  }
}
