# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.input_message import InputMessage
from ..types.response import Response
from ..types.text_response_config import TextResponseConfig
from .raw_client import AsyncRawResponsesClient, RawResponsesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ResponsesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawResponsesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawResponsesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawResponsesClient
        """
        return self._raw_client

    def create_response(
        self,
        *,
        model: str,
        input: typing.Sequence[InputMessage],
        text: typing.Optional[TextResponseConfig] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Response:
        """
        Parameters
        ----------
        model : str
            Model identifier from the ZeroGPU dashboard (e.g. summarization or IAB classify).

        input : typing.Sequence[InputMessage]

        text : typing.Optional[TextResponseConfig]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Response
            Success

        Examples
        --------
        from zerogpu import InputMessage, ZerogpuApi

        client = ZerogpuApi(
            project_id="YOUR_PROJECT_ID",
            api_key="YOUR_API_KEY",
        )
        client.responses.create_response(
            model="model",
            input=[
                InputMessage(
                    role="user",
                    content="content",
                )
            ],
        )
        """
        _response = self._raw_client.create_response(
            model=model, input=input, text=text, request_options=request_options
        )
        return _response.data


class AsyncResponsesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawResponsesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawResponsesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawResponsesClient
        """
        return self._raw_client

    async def create_response(
        self,
        *,
        model: str,
        input: typing.Sequence[InputMessage],
        text: typing.Optional[TextResponseConfig] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Response:
        """
        Parameters
        ----------
        model : str
            Model identifier from the ZeroGPU dashboard (e.g. summarization or IAB classify).

        input : typing.Sequence[InputMessage]

        text : typing.Optional[TextResponseConfig]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Response
            Success

        Examples
        --------
        import asyncio

        from zerogpu import AsyncZerogpuApi, InputMessage

        client = AsyncZerogpuApi(
            project_id="YOUR_PROJECT_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.responses.create_response(
                model="model",
                input=[
                    InputMessage(
                        role="user",
                        content="content",
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_response(
            model=model, input=input, text=text, request_options=request_options
        )
        return _response.data
