// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as ZerogpuApi from "../../../index.js";

export declare namespace ResponsesClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ResponsesClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ResponsesClient.Options>;

    constructor(options: ResponsesClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {ZerogpuApi.CreateResponseRequest} request
     * @param {ResponsesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ZerogpuApi.BadRequestError}
     * @throws {@link ZerogpuApi.UnauthorizedError}
     * @throws {@link ZerogpuApi.ForbiddenError}
     * @throws {@link ZerogpuApi.MethodFailureError}
     * @throws {@link ZerogpuApi.InternalServerError}
     *
     * @example
     *     await client.responses.createResponse({
     *         model: "model",
     *         input: [{
     *                 role: "user",
     *                 content: "content"
     *             }]
     *     })
     */
    public createResponse(
        request: ZerogpuApi.CreateResponseRequest,
        requestOptions?: ResponsesClient.RequestOptions,
    ): core.HttpResponsePromise<ZerogpuApi.Response> {
        return core.HttpResponsePromise.fromPromise(this.__createResponse(request, requestOptions));
    }

    private async __createResponse(
        request: ZerogpuApi.CreateResponseRequest,
        requestOptions?: ResponsesClient.RequestOptions,
    ): Promise<core.WithRawResponse<ZerogpuApi.Response>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "x-project-id": requestOptions?.projectId ?? this._options?.projectId }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ZerogpuApiEnvironment.Production,
                "responses",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ZerogpuApi.Response, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new ZerogpuApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new ZerogpuApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new ZerogpuApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 420:
                    throw new ZerogpuApi.MethodFailureError(
                        _response.error.body as ZerogpuApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new ZerogpuApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.ZerogpuApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/responses");
    }
}
