/**
 * This file was auto-generated by Fern from our API Definition.
 */

package errors;

import core.ZerogpuApiApiException;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import okhttp3.Response;

public final class MethodFailureError extends ZerogpuApiApiException {
  /**
   * The body of the response that triggered the exception.
   */
  private final Map<String, Object> body;

  public MethodFailureError(Map<String, Object> body) {
    super("MethodFailureError", 420, body);
    this.body = body;
  }

  public MethodFailureError(Map<String, Object> body, Response rawResponse) {
    super("MethodFailureError", 420, body, rawResponse);
    this.body = body;
  }

  /**
   * @return the body
   */
  @java.lang.Override
  public Map<String, Object> body() {
    return this.body;
  }
}
