# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.chat_completion_response import ChatCompletionResponse
from ..types.chat_message import ChatMessage
from .raw_client import AsyncRawChatClient, RawChatClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ChatClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawChatClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawChatClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawChatClient
        """
        return self._raw_client

    def create_chat_completion(
        self,
        *,
        model: str,
        messages: typing.Sequence[ChatMessage],
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ChatCompletionResponse:
        """
        Parameters
        ----------
        model : str
            Model identifier from the ZeroGPU dashboard.

        messages : typing.Sequence[ChatMessage]

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Optional model-specific parameters (e.g. PII options).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChatCompletionResponse
            Success

        Examples
        --------
        from zerogpu import ChatMessage, ZerogpuApi

        client = ZerogpuApi(
            project_id="YOUR_PROJECT_ID",
            api_key="YOUR_API_KEY",
        )
        client.chat.create_chat_completion(
            model="model",
            messages=[
                ChatMessage(
                    role="system",
                    content="content",
                )
            ],
        )
        """
        _response = self._raw_client.create_chat_completion(
            model=model, messages=messages, metadata=metadata, request_options=request_options
        )
        return _response.data


class AsyncChatClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawChatClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawChatClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawChatClient
        """
        return self._raw_client

    async def create_chat_completion(
        self,
        *,
        model: str,
        messages: typing.Sequence[ChatMessage],
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ChatCompletionResponse:
        """
        Parameters
        ----------
        model : str
            Model identifier from the ZeroGPU dashboard.

        messages : typing.Sequence[ChatMessage]

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Optional model-specific parameters (e.g. PII options).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChatCompletionResponse
            Success

        Examples
        --------
        import asyncio

        from zerogpu import AsyncZerogpuApi, ChatMessage

        client = AsyncZerogpuApi(
            project_id="YOUR_PROJECT_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat.create_chat_completion(
                model="model",
                messages=[
                    ChatMessage(
                        role="system",
                        content="content",
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_chat_completion(
            model=model, messages=messages, metadata=metadata, request_options=request_options
        )
        return _response.data
